name: Build and Release

on:
  push:
    branches: [ master ]
    tags:
      - "*"

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - id: release_params
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "::set-output name=prerelease::false"
            echo "::set-output name=release_tag::${GITHUB_REF#refs/tags/}"
            echo "::set-output name=title::${GITHUB_REF#refs/tags/}"
          else
            git fetch --tags
            echo "::set-output name=prerelease::true"
            echo "::set-output name=release_tag::$(git tag --list --sort=version:refname | grep -v dev | tail -n 1)-dev"
            echo "::set-output name=title::Development Build"
          fi

      - name: Build artifacts
        run: |
          poetry version ${{ steps.release_params.outputs.release_tag }}
          poetry build

      - id: create_release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ steps.release_params.outputs.prerelease }}
          automatic_release_tag: ${{ steps.release_params.outputs.release_tag }}
          title: ${{ steps.release_params.outputs.title }}
          files: |
            dist/*.whl

      - name: Publish to PyPI (only if it's a final release)
        if: ${{ !fromJSON(steps.release_params.outputs.prerelease) }}
        run: |
          POETRY_PYPI_TOKEN_PYPI=${{ secrets.PYPI_TOKEN }} poetry publish
